export const quotes = [
  '“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
  '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
  '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
  '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
  "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”",
  '“Try not to become a man of success. Rather become a man of value.”',
  '“It is better to be hated for what you are than to be loved for what you are not.”',
  "“I have not failed. I've just found 10,000 ways that won't work.”",
  "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”",
  '“A day without sunshine is like, you know, night.”',
  '“It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.”',
  "“If you can't explain it to a six year old, you don't understand it yourself.”",
  '“I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.”',
  '“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”',
  '“It is not a lack of love, but a lack of friendship that makes unhappy marriages.”',
  '“Good friends, good books, and a sleepy conscience: this is the ideal life.”',
  '“Life is what happens to us while we are making other plans.”',
  '“For every minute you are angry you lose sixty seconds of happiness.”',
  '“If you judge people, you have no time to love them.”',
  '“Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.”',
  '“Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”',
  '“Today you are You, that is truer than true. There is no one alive who is Youer than You.”',
  '“If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.”',
  '“It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.”',
  '“Logic will get you from A to Z; imagination will get you everywhere.”',
  '“One good thing about music, when it hits you, you feel no pain.”',
  "“The more that you read, the more things you will know. The more that you learn, the more places you'll go.”",
  '“Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?”',
  '“The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.”',
  '“Not all of us can do great things. But we can do small things with great love.”',
  '“To the well-organized mind, death is but the next great adventure.”',
  "“All you need is love. But a little chocolate now and then doesn't hurt.”",
  "“We read to know we're not alone.”",
  '“Any fool can know. The point is to understand.”',
  '“I have always imagined that Paradise will be a kind of library.”',
  '“It is never too late to be what you might have been.”',
  '“A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.”',
  '“You can never get a cup of tea large enough or a book long enough to suit me.”',
  '“You believe lies so you eventually learn to trust no one but yourself.”',
  '“If you can make a woman laugh, you can make her do anything.”',
  '“Life is like riding a bicycle. To keep your balance, you must keep moving.”',
  '“Only in the darkness can you see the stars.”',
  '“It matters not what someone is born, but what they grow to be.”',
  '“Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.”'
];

export const authors = [
  'Albert Einstein',
  'J.K. Rowling',
  'Albert Einstein',
  'Jane Austen',
  'Marilyn Monroe',
  'Albert Einstein',
  'André Gide',
  'Thomas A. Edison',
  'Eleanor Roosevelt',
  'Steve Martin',
  'J.K. Rowling',
  'Albert Einstein',
  'Dr. Seuss',
  'Douglas Adams',
  'Friedrich Nietzsche',
  'Mark Twain',
  'Allen Saunders',
  'Ralph Waldo Emerson',
  'Mother Teresa',
  'Garrison Keillor',
  'Jim Henson',
  'Dr. Seuss',
  'Albert Einstein',
  'J.K. Rowling',
  'Albert Einstein',
  'Bob Marley',
  'Dr. Seuss',
  'J.K. Rowling',
  'Bob Marley',
  'Mother Teresa',
  'J.K. Rowling',
  'Charles M. Schulz',
  'William Nicholson',
  'Albert Einstein',
  'Jorge Luis Borges',
  'George Eliot',
  'George R.R. Martin',
  'C.S. Lewis',
  'Marilyn Monroe',
  'Marilyn Monroe',
  'Albert Einstein',
  'Martin Luther King Jr.',
  'J.K. Rowling',
  'James Baldwin'
];
